apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.service.port }}"
  GATEWAY_PORT: "{{ .Values.service.port }}"
  NODE_ENV: "{{ .Values.env.nodeEnv | default "production" }}"
  AUTH_SERVICE_URL: "{{ .Values.env.authServiceUrl | default "http://auth-service:3000" }}"
  CURSOS_SERVICE_URL: "{{ .Values.env.cursosServiceUrl | default "http://cursos-service:3001" }}"
  INSCRIPCIONES_SERVICE_URL: "{{ .Values.env.inscripcionesServiceUrl | default "http://inscripciones-service:3002" }}"
  PROGRESO_SERVICE_URL: "{{ .Values.env.progresoServiceUrl | default "http://progreso-service:8000" }}"
