apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cursos-service.fullname" . }}-config
  labels:
    {{- include "cursos-service.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.service.port }}"
  NODE_ENV: "{{ .Values.env.nodeEnv | default "production" }}"
