---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cursos-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgDDTzDnpq+X5LM2ElufEjs/B0FtXu0TDGjxiyw6MOWkBTD6tmBo63RD57zaT8IpYbeZLqzoMAI7zozwL4ER9HnweE9ozRIBBKQiaTZqefWDKO8FFNFK4VL4TISheejrOvLoT15uYhIIS1dtPe/FpIZ/70wzNWjwopyHnsQ23TXmL4bfdAK4v7843lQJP+mD/c29jcgzKBI8ElQqnRCJmwqBma4ehQohTd1L1j3mGvylGJcCShy3BqCDIYVKjWoV4IemnGMiw/y1l22d9T4zR2T88mh5bf9PbC+k6kqJ5YrED+hNMexpVwPiw9/AG3te3aWF5w9soVEEzNbh5KIFra9lRS7HTv0tMlKcrL3mbC+aN9soc0hNUMU7cM5ibd2fWAenfiG6pBghpgSx/0nC1VAkGI3xKMhB3AsCtvhRZTePm6bNuKJrXP6JdEsQcMJeFw1moEt7WAcFD90oN2jRXhqgnZGObJwqDga+ovEQQ9lKqRYCcCxkGjmDCcEQEqIeltgkOUM9Ift7VJX/H3Ca2mxPkqoVBcC1Fr+yf2NRZ1bsQzDzG2+quZOjCLClGOoLg7KvcwHwFNwaoeeexXLpcxbUW0UlBwJHWz1UPPBpT0aemI7teXQLf20Xzksx8QVLVaXEfy168MylE8zntVfj7zgPRov5oXCQjoleCIkgqWYwKsEQvmVj2bGdyoBaTB8SaCc3QB1nGNB/kJ/IaXY0SdHSxYi3t1CEmTMObjonyn6jdjFws2Q26q68dFxy8Kgr9V3tIIQpNXqmUUBUVSb4ZfSbMEUMUUOcjVxuEMWlZeRWl1XLULQ1nBLrR8WjGpE8
    JWT_SECRET: AgCxvOxpwfGPuieThsovHGy94g9kGoilV3Vm/yjT7x2K5CTFmofzFyWWn0OyhaP6nFKBFtbjIftXBLHCQz+jTFsl77r7cBvk0/txGdrT/gOvccm16PleVr1g83cuZ1YGj1R0XNnxI4nT1ntgx1ryc6SYY5aCP3gDEL0wq8YJ8GT8toSsB/m4BYaEwY3lDwnLHZW5wmZUQDUXLd7iZmJiNlU5/BAFVe37ufErTtVpztJYNKl2Cf6UzN1nMSKVmQC/RwMALk+sVtEyZWcmatE8Gp+aVK2tfV0OKtuNW+8AXOZTvP0YtvK+y7S8SGuruWNNJT+EcvIO5A/hjKEDcTJOMeIqgfLbjHXRnC2arVAS9AKb0715hU4RmkitHyTcMND/NgnZBEpto6IKlQ9tAf9OGKb+wpIL9jfGB2v2RAyL05LgrTTfGYTI0B7MT7cqBjUFgBUwvNH6+6NOP2Wrx2zLhl0VfCf5A86j5u3RtZujFivA0RwkbTnNyrVkP9h3J8FBrgSRJPtvrjtiq5r+OktpsNFQvIKGQx1QQvRsYbcIXLdBGJ3zP6qv0dF33E9LZJFfLtHxdqzqxIim3xcVwl0Blk7+nN3SwNm35YwXbwa0zKmuNyr1qb+Ci7SHsqROrSFG57KgEzZRiwXOY/caVgcAX26tJz64dMDQBFrIslzlx86TQD01hWbgILEFhEgokyrzgaMBYZhlcl/XK5FIMZzIASklmGubDODWgLdQu6U6XqSPeFQs2A==
  template:
    metadata:
      creationTimestamp: null
      name: cursos-service-secrets
      namespace: sa-p8-prod
