---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cursos-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgBarMQcqCGS5wPV69gRBWLponCQv1lh5EhGc6Xg+BozD7uONAmEw5ycvB4XzUvarbKsTfWGsao6dANu36vRr4Zd6DoYRQtqrgO+mORLKqgg10/Z8XRgET9He3XSE4IYg7PzFg+Pyd/mgInVqHRlN38/puHMPxSVDPU9VYgHpYtIvJ+LYK4tme07X3FpNveBPmVmUSnXvacPH1RJH/66NHjmkoUbgk6n1Ah885mzI4CgTnyc8HSnYNFpMMsapP2dowUXwr8aoOV5pDQiwI3WGoQ0p1KzZfgF5QHlMruX9pUNuKZTxWzCj27S47+gv/lDjZHJnRXMr1py9HMCi65twSgzppQdG2Kr0gLlk46VhiADFOkkju50q4Z0r18BLjjlMXRt/TlyyWupFMXYc+IcnnuNmlcNojZ/Lq40u37FZSK+nPUMzeqyKcmr5gu3com/sci3TYPRx9boYGxqEZWhxSaPpN1iJvamXVHpLjrMUBxOD8nLbljORr6BfT/AU9AuZ8GDLBZDaixeKnuJeiiffyO2/32gNRcv+U7g7ufaUz9AlxKgmUEa4YZnOSwg8ncbsCPEEHUqQMfNeMIVQMCwP7OWmqAPYTaDNjfZm/Rh3+UQXxuwKUqJPx3SgunWjLs075+dYNXRi8KNnG5YPv4re3grYUjNC28DxFple8waixhncZ6/9+OECulPEnQQpnEdSpKSTocO5G5dZ3LqTONUS7wnI8Uw/1Ug+EwZTWkXDyJo4vZPXj8yqHENVyHdhRO1r3osDTXxlx+sp7crD02fnXu4GX3cjSoTeOtJC5pZhvp0Csw69cQat+cJZt8CrqEvPopKT7Io
    JWT_SECRET: AgDHAHZ9kLIs6Q4mQooghJm0uVb29kRmS2g5x/gU8cCchndIiR7sn1+ap7f/QdmGX1smAi3lil8E5fOdoM3Y+s5XGsuPgOontohyEDC5rfa+/hWMyO9uSgb0revVv6nDwv1YILAWZ7vHex//6DxK9Dlnd9VbQ9b//Vln1oaMvkzDd1LLJiYNWtFYe5xTmM7vUmIT+FHywdNDNEosrN8PP8n6phX7qprMR+WkAnrA2CZxZDfvojUNgn/CxcyI85GDDE423ED/O4YHfEtwSttlIJeGT+sJfwfp/iDcvyYb+P+Je+HpSDvAX7mlA16+tfBKXDqwPb9W3bG1mrVXTEJ6+DCpiwOu6oUIUL61bLM/891E7ZcD9Z5/sjcCs0R0cNdaZ0ZQOj/fHYo9qTBou/KszekvON+gPuIdAet4u3oIX6oYTXVmEvPowvc2SpGRF3r0Ra5JS59Yb199JO92WN7rNvPm3e57gT0Tgtbw4pdei87FiTXIj4pgZsOHpPak+wdJ7Dq8OwuVyCH1c4M9dT1oroKL6S+xgZJZ9/YP0MRFp5taYxaAbdrKeD9UXmkGrywzczWVBn65pPKOoAY0G9ekWwy0Doij30fv/uk7sMYL/J8TpEqr5oW4JBt3n35u9QUy4Y+rAF8cr00l4mJhu9Ux8iHh5lLmEQ2L106GQPmypb9jfF9kDc6v6gCMhUmBaQl96GTke+KHMUyZuyEpZEzgbbpTRSi5BhJG999gFDzBF494HasH+A==
  template:
    metadata:
      creationTimestamp: null
      name: cursos-service-secrets
      namespace: sa-p8-prod
