---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cursos-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgAvc/fNP3sGfVKypT+F05yg4VCHOCW4wCs7KYm4//G+iIaDQXmyVLyeJv44MU0kX/5x1etUQgOkK1p+DrU6ooeDMonBZ3Gjpl5W0ftWjcaEQc8rXI1jeNLJqnTC9qkjthC4yNO5/fZobCwT1zt9coiJr++b0Or18+27A5FI69UWlF2Ai36MReIO0DIC19kNITtueSbCO4BvrCHhObeTSfANFsIEJqj6wFbIAsUuzTFQSm1eD1y9MOrNeOAU/iFlbpISkfv2Q1UdPk1QnC4YlD96qNvcWATX86WE9qaAgGPrRxLan18YTjIfGtT2Nk61o/tuNvN+cqI7iW6w+kjNkrcGR2D59+33yEiMBspIWqmGJKW3xEZwvONn3yeysqrBPJzmV2MyJIxuvH+DeyhJe2Cg4P89G26n5gQRBFSpS6N2z2q3DwaBSW78ToHk4LU8K430HkLXPHlg3gkahOjt99wMESeuGKAd0hI2YvPUfB5IvS93pbpp/x7Ypoh6FeY8i16xvZA52/m8K3PiymHLpUSwe0K8bu3Av5h3oqQ07oZO5Ck3irRPWvHND/qXDJdEYPYkaT7r5citKAYGmlUJFIAJX529S0LWA3vIouJ9f2tDsVAi+2CBOdeQAuwCTaebczToPXVegsUeBx+/hP7K+mcpx4zsFkJlkTwZUBRrxvVykNhg8K8R3LalAzvT9s9DEs4F04IoLk9zyp4I21Lsv6+0vhRA5fZa32XV/NzGjidgMYMCuq4cb4HC29L/u+SNqx760CWGB97jKONl09InsOI3ccUwVg2cCHeY1d0xKvdGFxiVM5IUr+bN
    JWT_SECRET: AgAuUwoS28i2o6ku6640jrLdEw6aM2qhIxhz6sF/6+PLBrN3HKgu6cAvZL7wfq7SZZKLlJm6cU323Cy0cYJBEsjsStUrqZWdb0Nr+wyZyJw4S/nlZXJM7RGNrXPdWHxC4zNGYx9GBuor+6KSg45cRO02dIPv5O0MkOD1G//TiXGC46j7AHa4nJzZRH+OvWiPmJOdnBbxyvDlivsaJViyAbbsOlqNu0uj91JIuGDdsU5rhzHcH4iVZYE8Mjlik83L4hQcnUCIgIFbNzPYb+zXdq8UlahLsUsKx9ZW8JemEOs9xMIZo98rolwp7Di5XDRZxHFw2IXHc5HHUkAiERNfYe5ZQy7zD/eljEzCSMvZUdhTHFelUTdtMs4gNc/Fva/6Ftz+yizQA+0BGm8zXGfUuwOFpADH86iKZkY/LkVU7WcVyb4Orbr2EAJvq2FczyUzKVCRLAGBLyu/Y3iOl25q3xzOF+OrRFfzyFNUhvHKLJXQvuZOLOAgl1Ps/iKEhKpUsJ7ZSu8qApne1PVHcCcciv+/TqGX/XQVIqRgHyNZE+VEzxNVoUDH/LN2957Z2s2wttC6J/nokNJx9ZAb6+b7ADrkUEmQNJgTS9Cjdufo9jxoZALof4Inx/FqwfyJYDWb20YB+ICtbVi0JGqYA1/nLWy8d/3VBT5552dsJqVyLIow0GEVSQ8Hu2wlOticnrS7tx/BncFc/W62d5YVf//yfyMYvYp5BerLh+7aRz4KY2LETW3v
  template:
    metadata:
      creationTimestamp: null
      name: cursos-service-secrets
      namespace: sa-p8-prod
    type: Opaque
