---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    COOKIE_SECRET: AgA3gcsPGAYLefa8BMDjTj4L68+R8LYjd4hrB5iwoM/g0r4qqQNFE9FXSviYKQ/cTkUkDqCusCxAKr8s7i6WpCGxkdk/n4mawIwt6Meh7q5o20MX28Mg9PUeK0HtPqiQzas+X00F2O8xt/4DB1+fD1SwMtS5g8J7JZlfoYSzVOcqxojRTYopuPbtNeXVx9mRlOB+Q40C1IxmVamE/2ZjpJ2sz0lUW54OzRvlI9wDu3F1HdCniPmZOvT8ESUKpaKXAr8f2iWXTMRmVDNCTfah2CO1O/eje6iHdICedOfYQog3LHfvWABqF9JvWlqp76BBUXSdPTGMPTXMGtScboNWZeL5AR57w64W6VP3q1XcdO/l0CysYobZM8iu7bpll27iv+cQgLDNVWcS005OG72LJlhJe1Ytat9dnJ1jT9A/i30+PTlDsq7wkQOlfrE94KFNdxCfw72Xh55IlCaESelwlNPBUBwQW+liI1hECAQqWa7Dz0q3xhnsRCnJSkCZJAR5L82sHTt+2QKz/JAhS4RLLnW986wA2HPF3o3MPaIpFa4+opeSHJgzueGWYHPmrnMO6JP3+UvSGqn1nherLfT3rBj3Erff86hCdiVfW7bH+iKeyLxSGxIa6Jt6A/sj1B/qfDCz9zPOYOjj9UiFjqC8Oy1cj7/6jePbjPN8FUsApc7d8DXIlV8dwlD3TuZ98XwbZyTZzAzAgMn8kz4fi7JDXYqgQ3HItqBj1f1B
    JWT_SECRET: AgCk3Je56//I0TCMlb0BT/NpvaulxYLt9cUfDrXF8a4hlPETMsvVIUPouktASR8GWmFDBKpMwcl+KERnEpdoDpVuI9DhrzOqQKFKecBRaZ1t0cVihPn5lxaqFUXppsOucQuxmsx8Wuzm1ldcNQYWWJIKy9uuSyiVXRWJqa+RSnGQceO54eVTkBhaor8QfPN2rchwiM9Aq/p2JV+N50x/uTUWesJNZgxN6pF0NO2m6hidJ4w1tuJiRN9qeNZxSIHQZR1woNLu0222DYMGr/vFZGW+nA0Swd67nZhd7M9s7QX5W6keqEZ7vnRb/NVACZDLsP+oUPpJrjC7y8NQFGOlcMfSdbDPfK4dE158lTctD/FTmDy9ZT363PIGUSUXi7dyC2ukJTPBQbntBVh6XZy4GQDTybWIR52+Yi6yLYrPNYM4Tp8fVWkVC0NJWEVodkaWS+3mVGcAcOEOJXIpoGIdgsjOwHv1bJOSRThK8NDFsL8LACtukUfrShIV2+VgH8vYUeP7hZYJcQfHAvcAx8AbOZCw9QgoVkyWs/SrAE7KsF+ViGlE6DU0qL2Rqt4DO7x2RUQ3B0eQ3kHLDicje1wWilcNEQekYb2k+jGZiOde9xRPSOCsIjxHx5fUW8KDxwSEw2vq3QuNXlFmumT7GH/YqLFpjYmPYrLP6A01wMVpI8jl2uZIKr1HLkji1Q2+am0mWuC0Mso/6ycU79szs9xisnF49RiI39Q2NH4zrAVASrnesyol8w==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: sa-p8-prod
