---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    JWT_SECRET: AgBI6WJ6+M4B2jhhLzg17eBLk1yvnYgF4SxnyhoFac1m8s0vWyNdNdehpkFHJ3YZ4IVGMGslB/r9ysu+Z0Ii1ClZ4avyQ10JYzUseCB0TUfT5YJPJybqDJYpJIQcGhVo6XZ9vZlBjHY9Izk4MYrn8s1dsSKwl5HIppp0SCEr3BFyGe3rgecA+ze7QKftmj7s9Y/MBF3p1Aqnve3+AoDltBSok5UECVW4kTDalf82p7QJp9HwSVIydeu7xbqcOi9WOm35+H7XZlaXGqT8c30jwg9KaY5X/b9yjytnUok9YmKS/CEADEUt3dfo78DwiHVcpakzQ4MwnCfChI1uMDoahmfnjS87npLg1Z61nojrUCUVjpOqJR58wnDU3Cu+48wYnPrhQmD/8gT0S/L0ZUmcIZa4ZPOK7HABmx+2klaPeuclb9YeEnrKVGGW+layd1vvzGX4zcgvfDKCHq6dkKKVKGuMzTSkB0gzOIl7mzgf7yKrQJBIO1vNoxZ5VWWAM/KZwgH1ItjfFVtpypBwXr1A9DqMsFi8tY/FqkIgWUu3N6jWzoP5OxC9RGpUBb2rzyuIL/01x895nDxiJb53xKG3M47EQlXqdEm0SpYEADoCL1K+BPkIipFCzrK1Cl5Mhx5Z+hb0JgvN8HoUld99LS5Aw6eDtEJ1vAchYvuvy6PUg+TEWukLiL4oEK3vz4RmJAksdfAf9tUyxHEqDupiaTejqJIlqoFjCJG4n+DD/OChvxMdWP8S
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: sa-p8-prod
    type: Opaque
