---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    COOKIE_SECRET: AgAjz7xHYw/28h64I7xQWQBxY6GJhvBn98JBFt/MIt2MOMldnSXl3YenjFOceXqFYT2H6uGHclIOS3hqnbPaw/vtOJr4DQGztnqTc256xZGtz8iHBn27cTjArMbWHmsiczdReDSaEdChX36TvCTxsHhXVIuvz9mWmUoog6QuzlkPjbajeBZooHGyRs34F2euylTZV+oxS3trpw7YZjs8kY8XigGkNI2lAEB/podsx6EkXOsC8dWK/py5bDu0PeMFphVTGOErBVZvz5T3bJK6WlKuKsyY769qnDDnQ5cISOulX25Mp6BWGtBOovy5elidbHzSkHEiQdTTiufg+oDnV/xoFkyR+AcHZku7f+KnE+QvmXQT9B+2Egq7p9GBoJrsvbRUS3AzhXOMX280A24oqI4wM5lCuOs6Q0KQnWbmKvimmDEKPWrY5dUZF+C0PjLOwYLuiBPtlWHGspu9lQ7kSWP4fbBmU6NAX9sN7yPxCzw2WlOIfVTbILHrchwNvd6w1V7B8Q3TUAPxEQuwfgMlz2IZKYbfXAxWoHB5MkHHrDQrr97mqiVJ5Z1VVqsa9HSJ1Xj53q6vhOLM3CXPyxG4rVcpaEDvEK/i+pgRpp8V0dnC0hmOfZ+1cGEBCSZFOuNYtAB1/mH8rZPnMFckG2/0PrqGgWne4cFPw4STwtqfRyPUT+Rgsp7/Mv7b1G6mT32eGh/1fc+/mDsqPrdC9naqV23X+Wjsuk5J++0S
    JWT_SECRET: AgBIOR26KCo/v9azN0ejPdmPcvLnDmuX5aLcc4O7Gt/QmSteGMfXlEFUEP4OiAA3brTNaAmDluLXNh0NJ9gzFRcieZSTVuOai1LCpG3SU9H7dZdOYeo6K1vzoepGtA9yqqM6xlpaGLij9icZcpe0GfkczggVKFm0XhiZ93Ga2+5v69tX4MoAncpCcEMHDjw2VkDCYO6WB8lSxg0WrWobkYDTAzWqb6RVmdQ4vlloZJqnmRTf9rkZDqgocC0dJXD1GC3dHIcRnrww9n3Por9W1dtq5qMfjrLjIzPAaMG5BuQYvhmPPm7d0XSGA6SSaOJrIg69FYoi95v9uf2GoUO0Tu6YiQZpqIPrs9xp70D+DcGxYGmtdE4ul1viiGfCtWxuaErufWdhPoTyxty5XG+est4XJeNf5Xw58iYuKVpWasTSKJNVDFXyX7D9WwDlOtm4xpbl3ejOTqIFMRfMNMRMMRsHPjFbeiPTug0D3+skx0FWzpZJvuoASIO+y/QpsuEMxrpdO6bLilos8M7AmoO0w7fRXsFQ3H8xITZQqbzl0UBRX/MYvVxGOl6FOwy3evBw+XzsGUAogzWK0ZE/P6vl8r2uYZJwtP/UEvnaktAXRpkYGZ88dMYOd3AXly992XR0o+B+3NTcJ8GieILkCR6TvH36apYG2iXvQkhecUQx64TrLjutJJeqizEWjjoqRMVuJyLB+X/UjH+EdwfLHNh38RaP4Rv1yVI4ukt9zztfNqdoejTxDA==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: sa-p8-prod
