---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inscripciones-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgCCRNZRAbDw9Ibn4+6g6dBxIBzLFXbgRpKWIbC2n210V13lYgvqg8F7zYg+VopPtRzzu6xfITTK6QdK0H5YiyJSHKq3ddmTAHAGd8i3hQogdoZzpqEOgnhX9GujHt+a25rIUK0DApYrSHKgWNEP/fHZa24UEuxE6yV0Vld4vVjFQ5e9yYaslQa2eAtVoYTCkWNh78HG3BkOj/pp5EoMyMZwj3gJguUMaR1YMRf4c0bgDMGIIYnM5bt8ePCmPPaUVZpa0ycQ+SbeXcAAJPhSZYW1TMwKMx/Ai561siOglgwH1Ox2U5vKptQ2uBLdPi38Tyz4mamS0UQDwm+vpU0Op+LQYnaNIGTEIsWWflsFLlWfFh/Nid1iFbCKXobQO9Aro6QEEFFq+NA9F3zotrTjv92UHI9GdfsnInINKPT0ghh0xFHj5gDhHCvycvWAbrsrvf4iKjSvbrM1mUbmS8yK9pocRqXdWexx8DlCLZd8hEl3jvLWGWjs95NaDsDUN04uCupKKw3eKq8SI0a5tEaVWxCB7aePpFwGHhBrjHd+AfK7YC+3SiJCwVk+LfUqyQ+HZ1v6kLFSIjcQOhzxknQP5O/f5GA231/9ChiL7rZnOB+6kj+J9tWfdegq6ZrMMzLaArylIQbZMZAe0npIjRcVBF1Zruu9wHpchfK5xDS7sGWw4g+N/YOadeFOunk9xcP8RLa2vKJaYoRGiCAhlAiXY7AWJEuyrksCiXzHKz0+VBk020jjNnmsJcn6SjS7DTpcUiez7Dkqe7SZWWavmhqTB4Bj82JdGzHIQ6n/0IdJ85CU3a6p0n1cAY64Nr4O0TMkYQCqD8xCHw==
    JWT_SECRET: AgBSTZi5JxOcEdn0gdh4kqNyXnTNTZkQnocpHaoc3JdD34U2pj8yvuqZJRG84LxNZXjdeMDwMwNcc0G4VgbuD6wN6ZXTlr1itK5mbROZb1rHk2Nq9i4b9CeXeiLVBSLalQxnV5P/qQfUGVTwOA/inckE2q6krUtU4cjWOlr/EkI5mfzS52WvX2gii0JBXr/BrWG6wieqRp1lcs3geZdPKpfcDmvmXf9cRkPfyC694+4GKYRrf3BOkOUfj7vglAlewJS9r7hD2M5x93zk9nJIE1DWGcxn4jcJdrQMFYmejDm47lSMiQld4T12fR4qdacazqCuoMz3/pdngl+9sbR7CasLRv6X64taphBOHsJWG5Z8hSp1UaegzGZpbDCHoi1E9GLaEqhcl+L+boG5fqfmV9vy1pWfAsFEmGWvvLOe2MEo839h5QpnYDo2Hje5WBU6Cfs+c60QeCAR1AttZFJ/WcmFFuSmvZaT6EfE1cyurqUQ9K/kkHlLTky7mplsF7XVS1p+L20mdWmHkXAqiHHwVRkAudt9KxjiqWKhFYoqmHG5oCd++1YGqVLCHo4cW0ASJzdHt4IGIXVWAn35zZ3LQ5rYknryCEK8lcsg5trg5gol49ZGuOFSnrLGIn21OA8YKeJwmHJf9lX/bD9B1D11xi+tyoGYW2cgR8tQyCLe1Xew527FWGAX3/K15uNT8hWFhsLeF+p0QKqE6i34Jd//D5gQ03GKdQ4oF2+ykz8gwJ9CKtHAxQ==
  template:
    metadata:
      creationTimestamp: null
      name: inscripciones-service-secrets
      namespace: sa-p8-prod
