---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inscripciones-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgBs2OSnPrM+2Wf1Z/8aH8NnLZIWzLrgEQ1TiTmnLj0s1N4zKb8Gku1Xmfi0M/JIabjMM30/1nFQxPmTM9DwPA2KCHij1q3Q9OrKbPqUWLlZWTWm36664huWU91gOTK2YKXCYfLJ3ivct1+/mrR9dHrhWRue247PyeRzRq1B3VahGgTmMcBPwBN05bSC74jbGkGRBHhkSG7FUBQuB9c77h03iLMRAhzkNMOShDG0wPUD84ZBvD7VA7VQMX0Q+8wtJ/RGBKzUTLkjm5UQJMaBQfHDOrK0ZxjfUIn7w/nMR18G+qPZ7dd/N8wZ5RIsAHb07xW88QHSuh7tydn1geSt3nzAY2glmCqibmtkuhbk2EyHjWu3fKrjkxnpb1gYEpjjQtz8/9HSlOw/O6fXUv/gLCdgh/WH9CKgCwV1tLCpTgwoCjgblsQn/WWrCRv7a3WWChz0MSLHzR7ynTt6TAvBJsGpfPgk/JeWUbDVC6K0shthybS9uiMYBVEy4+dfQLDp7k2Rx/iXUuFSM2Q+HQ7Nb4tse3db12xySknT3qfYDNToDUftTjR6jHpBcD3SdyzxT2fVAw/5fAj9allHLIq0dSKjTjbyiNSpyXC56mr1eRWa8TmPm4lrmg8jgiuvyLIiuzMXDzZomDW4WIu1WkFLpTrE0XG8eSPnrCnaU1tlyLeZ1AnJrHqH5oX27xHdKD0Nst3MUtXkeuJknr4lReLDRQenqSyokW7BVfmYYQWtxsnU36gkhqtWm94eLu4dijgsOXnqOXvrvdZ7FcG0HmMVzju4CcjM/YC42gk+wUF2pYuYcNKhU7SObnwJNQUnAD9aRjgnkS5nbVqR2X29eQ==
    JWT_SECRET: AgBakWREDH+gDx6/j1mKQjLTkraJiqC0tE6gzlzGkw7MrKpGZh5N4eGNX1dw1k3SMLn82lVMN2VzCETTRC5dJLOkhm9Ft1inJ0D910fWczf5TFSNqydSvyzhVq+Tq5paOprzcwYsG0jisz5Haj5isZ8bM9z3najG5uKsj03/jhmQIGYpaTykq/TgkFsrcP1ktpKFxGBYm4/yIbDLqf2+mFsU6+ucBMxKD1Idx5bQTcKdS0kVl8AXh66WrpD0n3COWTrDzIIdDLfhp0RSLsSH/b+nuCdj9S9Cxwr4lBZAp/478O3alI5o7vdig0lceRXLvCd9spWI60PnD5tal+1wGay68ib/jikh2zPLCR2zsBAvKEwU8o8tktHf+iHYaArid6iQXod7u13+FOYjZOXHFMqGFFsr6/aXUT0/a9wTxDmH8YjiaPaA9sqh6dwU6rIryAtp2iyQF6G5vperzlhAwliS5rHPsWJJFAFQV+f29z7SzGOksq7TrBWYpg+HO9iiAfD7QaK8UBkiKvIwJljadZPTVsfyoxafpiDQrvQt3TwN3sxRITzZOC4UBxMDxifwn14nAM2XA6LbunRiOcxZQ4jQB+EKaWzodQYrrw2moipVTeGCbMs5wz1amUX2U4tdVA/Ya62GbTyJ13GcB9LuucIV+CsjnfEZDWN0zh4Ry7LN9wMkr+yArn1pR435zNGg7rGmIaKtesnBL0NH5lvX7YKldeFIU92q7/jBsQwwSpRqsEVwwQ==
  template:
    metadata:
      creationTimestamp: null
      name: inscripciones-service-secrets
      namespace: sa-p8-prod
