---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: progreso-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgBT6tYAZvBir9wOn+pbmoJIJUeKaFaHsJOTLl2fIWAchweadpnwzXBQwc2yB+ncqwc8+MiKK6oo/4wDb4nfiskXcwhpdd+mJhqz6PwHA42NO/U6GTS7xZ93A5ZH6hJxRMbUrKcdW1HaKBBTrVuCAo24mBjgGP2cBA0MrI40LeTeaNfgYhtZjW7UxEoHEc9D/NO9G9kFKU1Hag8I2TGjUVOAZNzErUO4kza2jiOelfLx0wDQ0AHzaCE4j5NWHGbupACUdxHhOtaM6UOplXfHGWb45wir058dFaNs3XQCGBO+IY/b4O27GTLX6BaKLlWShX1cj1HYSn1SUAI0nBSvmxT3Q5lU+VQLvA5eUSCuO6x7ucm2Q3LIhkOMaNeBIQsSIHa1Vfgrt8uiYnIjuKx68u4o3aiJ4V7ha3tkUDYPGp/TEK+JJJIzTCm+Nrc9KOFVEFrKZ8GNkL02Th/wVygzpSDjt70/iEFcZ5w0lYTAfaawVnEFUROJbidsJ8rLf2YhDale1+SK+9ZtvSj6tzqKVHQQjD3+0qjIoO1XgHNK1xVgTHfqFs4RP9ToMVesROeFHHzhaff3A3fcjeD1xIRqH6lSXvUjKeIx5+JIgu+q8Vx/S/242f6TAKO3tCDqTLQdYVl40S/4VwGwXrOPrjFokVPTeHMA9AL7YPX/xibQxRka3C252PDLjeWqhO0xVOD3IcoX8CapenNwXN5F/tFpPxpgXtKYIVX8m9T+VNZl4UvMBz5dzfHZGMRlbUiOl1c1YpsD09WtWzPFhg6StT2Eq6CE4AOqXMCW6dMEwpH79f97w3vQ2Y1sCxoMqJbr12+YqbkN
    RABBITMQ_PASS: AgAhooxABi0pLayC98WziYv1+HuagkeO7i9CcTR9+sbM2ExMw47Qlk2mCXqkgPN7H3yCGNWsGIIU2P19pmn4VTGBx2ztCv4eJC1Kv9GwGu+b1AYi0JkpBhCH67sK1VrQ1MGryAmw/SyDT2BOE/aNkBOt3DOZIUS7UT0YVwib4FALb6yNb4unVcUGPNNlXQLGCcBDSTQYNzV7tEotS8f6LcWDqjjznaSKJSFOA3TJHuGQv7LE6GSFLXSOED8GPT64OdB3W7eKOhQIABJ+zhcKVODughtuXLFlRbC2bZeYP9X9opPot3lB7d8MGSmlbq9Oxn5qY9E7YFmhcQZe5TjNn/uXZX881bVSUW6nxsS7QSYupdXF2kT9dcXku2rYOomRTBpiNyZp93nfC4Rnnv4/7JjIJe31WEURdQ5Q/QCxxiZ1qOTVc9nB9BHPSa+0RWoqmPi/eZ7gZmEUESPK0R5S/FzH1/LimxEG1SKudQd2B61p5hXpc8iTkU65EEjPn8QrZk04xShVfD++u23iklfbdKMziCnlD8fo9ODd3zDsHa4OZWtlhl7BU7SsB12rHcWcUWMZlsvuYPRy/EtKeklw7S32CC7st0lnlldHkCel/IJ2zE/Ch/Lp4hYoVAp3tM5B+s8tvussCmORrFdE70e5C5RKE8U72dHH3nU9K++EMIJ54Kr3mYCuOAzqZ/KcTZ0jzEp3nQpn3MwidfaFpA==
  template:
    metadata:
      creationTimestamp: null
      name: progreso-service-secrets
      namespace: sa-p8-prod
    type: Opaque
