---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: progreso-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgDO6fN1qtROLlWKHLm5pRcwJWcH4biggkT2Kx32bW+P1hueSomz2Zg9KOGfTrGgXaFzo9Zvzr0qireWRox7er0fhInNPfQVStMQWSq7XZT0vTCUcsBGWBMvHc1TGDSja4Dg726/NsQRVjGVFPgdnb5vLMRUhWBZ79D6Ozi0swQXJ9T4ob8pSoKR3dWweHpjMGn/mohX9uP9oohi1WUTcLzHaPUobAX/UhJRiZc+byd7u/ZmEyEGPM7iL87qPAXSV9QUUpQLxaaLlb8TnfryURfNQxo354LY/RzGfEpT2qdWn1nPQFfOlieQhq/vok8qezjIFZf/iVQ1OuR569HOeqJpZZ93+bv0czpkNJYuYTMXPdNYGkRALoyO3/jQFuBazrzAfUj3/NaPHytrmgaWnV0DhwkHopN71hcaCkXj1x18irCHsWANvZmyWpkoP5SBN9z8QUHJYJFPzNjqTTreqyND83T1uIu6e1VFnbUxvdA7NtCwe22IQPGOLxZNLtIAGNPSuc2v1BZc5oQFH464ynXgUS5IV7oVqxi3wkU9MNuzIIHrzrdYQ9KEmiTweKjp87fXv7hRdGSDG2TYeE1lETwvLsolQK2ZRilZCOdEezRL1uiqkcuwOrksV4+mduZ1sCdo+Ul2vly9lMlM7Lc3pCIy+zPkUgrqedMLZnJUwwVBdCAIQWkuiSwiPCmWrI4jFsd8cMkpTaKehIyBfd3q40vr/CMZIj/Eixkd0CgLhZpjQDZTU762SD5kImsA8TwcN4d04OYK9npCe+p9d7e3dOnY7dIJPE1dd+erj56zIdc9DvkrY861FD79hc61lqYw/UQ=
    RABBITMQ_PASS: AgAH70zRQjX/wyLjVm8b3utd2RM+Fr6ZIyar+FcMrkAtLc04ODkTtE9twxaSAawYkwaU3jZqbFZLmG8jChiwO1g9GmxtsL2CEi830wkM4cSvyWTZ2/juAo0WfCxt0vsCPBbyy7lL+z3jj9RbMXHjofDsItSU2WOELEvdymoopjQHzS1iwkE7ZrhBiEVWZExcHa/hCDGfaMk5qVFAJWbMsAbgGzv/Gdbeu5qwOMmnSv+EQxjEjW99691QnfYD3T7QM4CncXO1hh6oIW6q5EcWkMjzagq0NDHRcxOjsir46Hj5Kg3fIc26RkDeYsToOvxSspkYven19pQp7aZnQ5H9BC1lGctccBChSxaG8VhVp6yBL5hGBQevli93vGY5jBe1HPWhVNbq0daafROEDf5tLRz3Vck6YWHFWTTIsg0xLejJIGPJSOof7vgPRHuLlxccWnd6jMYCfptKuYZF1+GQdAxD8iDmv5mR3VDZZbwABVmfrXqiB7rMkwyzL9B2Gq0Cd87TtStuW+j5pImKnLCCxk36hSYP9QZkbBt86OJsUhfOnx6pao2DRLnq4opAiVp+enzy2VjJ5JUMZ2iHcJ0/l+BM/3H12dkzS1boU3bdnD6UwEu4HXC5jsKGTtcBvsDjHO2q9w6yXEGB6mjDPcGEcNt3t6cqnStT7CAAgdBgYckV/lomFvy0TKULe09Vv94mw3sZvB/tdIk7HXGLnw2ccbB/ew==
  template:
    metadata:
      creationTimestamp: null
      name: progreso-service-secrets
      namespace: sa-p8-prod
