---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: progreso-service-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgCSgVuDUIU8KvQQDudbXhXk8LNekSIva8xkVsSEzYdm4O5uXQea1F1jMmbBOSjtRyN9TrfphvfCpB++dC/NXsftl1AXJpQHcgzburMC9Aclc/e5mIRj14cHGhIuxhtxvAzT5ahXoMqfgAdl249MbnpCPLI7bSot2XzGOO06L3IHhCMwyQDZmy0tiXKvV8j7bEofJII57IliKgV1LxMpBCwKBEtPlk4PNkCiRzfLDceqYVdanhTeSNupm35gMOHREQV1NEUchaYSvSHwcfuK7+C9ONepUoyNydwRs6WGA31oB9yzelVetS2T+p+FaBvIQ2JGZh2LgH4QbNFnackvQfIbydM08ZT/jOAL1g3bSS6ArolAbcGOpaGscDJlz759cvWfCtyLvS7OeRVfuqaw+8XFZrTzZ5QU444fV7Fa6nUml6pmlzPPQ1Kr7QFgdZ9CWNbCif2CvH/ovcCe4oEdq4qpPenLBxEBE4pcwfkF1PQHykQuj1W4rlMmr74Qz1sk6k6i5lY3jNjC5byIwAfj2jy5pBau62oazkfZ0JPRNdRte0o3+uWBeAxzj89ow2nRd36vgASvkKP2DcwzngYFm3WCk8vEv/gOkyYUfpyW2BCAxAkqauVe9B/hbiFS0Lb9FGcjiYDqA61FI8B7E/ZIKvMQjd5ITtUF9NhbZ0bViOjywkc5pDQnWalccpfmFLkWEG9YVncjWT1OtU4ALHzpdFG7fGyzvyKvofBqfdU/84qLt9mFJcaA6/67EnN38G+MlBphqi7tr/j5jUwR73NqMXI594Lu197sxlyU18on5bXosfIZi0IosbLd4i8v6RZGINZSGbWd18E=
    RABBITMQ_PASS: AgCzfcQJ8+ZX1EPrLbxOyjTxsAc9vaAOAw1Ekavez80yzpfaTc2jfxzwghogurvirn4scbGzkzKnKoRp+vu9VJsVKLcsrnkHce3zx4i9ExD+lX4nHqt+Wjxdul+vle3JinwU4hVf8RuJAIDGt+2NUtSqL9B3AMgRvdFeQVPz1n5GoE0J8uOOaPnxDyNvAQe/aNIOZseFiTxoZZORGobbtTv0cMl0G9nrJdJd6SszUC/Lbps36qNEVom1vpSGq0RiUJj2/vsM0tsBRkeseR0hVZMzh1MI7X3pBZ8Q4SgFWxXW7bo2biVpLNQSLOvMrVKjV5V4f57M0iAkJZMCV7+UY/KA5WNj6ioFD3PCDPwB+yXtzvEiXByxfVx1P0MzqUxtrxeC36ys8i+QjzSLDiJZ3N5OifaRrTsLH3kybc8FwtpqBfgO6//3ZPCxW/m5l/jLcle1COK0jXvxXmCyXruvISsIxwK1TNORDh4kqrpvYkjO7SexNqmoOLJWETfr5BICKPO3Z8W4ddvpqm7abJj4KhDJjvGpER23FtMWuOyQFiQX731xfkD4TTZ/hwoGjK385UYCaohsVZQWl1z1CNIiYDkZ/Sr0PeTkj3LZ8HJFG/wEf0asRxb36iTEiRQAaMGrCawvdC9aDhiDAK/0W4FxiL91mSOxmZK/LH8EHRALVMjEmWTYQGSACV+uK2urFBnQyy/YVxDPSGadpuefNiASfXXSob9a034=
  template:
    metadata:
      creationTimestamp: null
      name: progreso-service-secrets
      namespace: sa-p8-prod
