apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inscripciones-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DiegoUConstanza/sa-202300601-gitops.git
    targetRevision: main
    path: charts/inscripciones-service
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
