replicaCount: 1

image:
  repository: us-west1-docker.pkg.dev/project-d92eea96-0bda-4489-bb7/sa-images/auth-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 15m
    memory: 64Mi

env:
  nodeEnv: production
  jwtExpiration: "5m"
  jwtGracePeriod: "60s"
  rabbitmqHost: "rabbitmq.sa-p8-prod.svc.cluster.local"
  rabbitmqPort: "5672"
  rabbitmqUser: "sa_user"
