apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "progreso-service.fullname" . }}-config
  labels:
    {{- include "progreso-service.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.service.port }}"
  RABBITMQ_HOST: "{{ .Values.env.rabbitmqHost | default "rabbitmq.sa-p8-prod.svc.cluster.local" }}"
  RABBITMQ_PORT: "{{ .Values.env.rabbitmqPort | default "5672" }}"
  RABBITMQ_USER: "{{ .Values.env.rabbitmqUser | default "sa_user" }}"
